name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker build -f Dockerfile.dev -t frontend:latest
    - run: docker run frontend:latest npm run test -- --coverage
